import type {
  AttendanceSeriesPoint,
  ClockRecord,
  Employee,
  HourDistributionPoint,
  WorkSite,
} from "./types";

export const workSites: WorkSite[] = [
  {
    id: "hq",
    name: "Matriz T2A",
    latitude: -23.55052,
    longitude: -46.633308,
    radiusMeters: 120,
  },
  {
    id: "training-center",
    name: "Unidade Treinamento",
    latitude: -23.561684,
    longitude: -46.655981,
    radiusMeters: 80,
  },
];

export const employees: Employee[] = [
  {
    id: "emp-1",
    name: "Ana Ribeiro",
    role: "Coordenadora pedagogica",
    email: "ana.ribeiro@t2a.com.br",
    status: "active",
    workSiteId: "hq",
    lastClockLabel: "Entrada 08:04",
    todayWorkedMinutes: 281,
    dayStatus: "present",
  },
  {
    id: "emp-2",
    name: "Bruno Martins",
    role: "Instrutor",
    email: "bruno.martins@t2a.com.br",
    status: "active",
    workSiteId: "training-center",
    lastClockLabel: "Volta almoco 13:07",
    todayWorkedMinutes: 322,
    dayStatus: "present",
  },
  {
    id: "emp-3",
    name: "Carla Souza",
    role: "Administrativo",
    email: "carla.souza@t2a.com.br",
    status: "active",
    workSiteId: "hq",
    lastClockLabel: "Sem entrada hoje",
    todayWorkedMinutes: 0,
    dayStatus: "pending-entry",
  },
  {
    id: "emp-4",
    name: "Diego Lima",
    role: "Suporte",
    email: "diego.lima@t2a.com.br",
    status: "active",
    workSiteId: "hq",
    lastClockLabel: "Entrada 07:52",
    todayWorkedMinutes: 378,
    dayStatus: "missing-exit",
  },
  {
    id: "emp-5",
    name: "Fernanda Costa",
    role: "Comercial",
    email: "fernanda.costa@t2a.com.br",
    status: "inactive",
    workSiteId: "training-center",
    lastClockLabel: "Inativa",
    todayWorkedMinutes: 0,
    dayStatus: "absent",
  },
];

export const clockRecords: ClockRecord[] = [
  {
    id: "rec-1",
    employeeId: "emp-1",
    employeeName: "Ana Ribeiro",
    date: "2026-06-29",
    time: "08:04",
    type: "entry",
    latitude: -23.55046,
    longitude: -46.63322,
    accuracyMeters: 18,
    approximateAddress: "Praca da Se, Sao Paulo - SP",
    ipAddress: "189.54.10.22",
    browser: "Chrome",
    operatingSystem: "Windows",
    device: "Notebook",
    locationStatus: "inside",
  },
  {
    id: "rec-2",
    employeeId: "emp-2",
    employeeName: "Bruno Martins",
    date: "2026-06-29",
    time: "08:18",
    type: "entry",
    latitude: -23.5641,
    longitude: -46.6592,
    accuracyMeters: 42,
    approximateAddress: "Av. Paulista, Sao Paulo - SP",
    ipAddress: "177.43.88.19",
    browser: "Edge",
    operatingSystem: "Windows",
    device: "Desktop",
    notes: "Registro feito na recepcao.",
    locationStatus: "outside",
  },
  {
    id: "rec-3",
    employeeId: "emp-4",
    employeeName: "Diego Lima",
    date: "2026-06-29",
    time: "07:52",
    type: "entry",
    latitude: null,
    longitude: null,
    accuracyMeters: null,
    approximateAddress: "Localizacao nao autorizada",
    ipAddress: "201.22.17.4",
    browser: "Safari",
    operatingSystem: "iOS",
    device: "Celular",
    locationStatus: "unavailable",
  },
];

export const attendanceSeries: AttendanceSeriesPoint[] = [
  { label: "Seg", presentes: 18, ausentes: 3 },
  { label: "Ter", presentes: 20, ausentes: 1 },
  { label: "Qua", presentes: 19, ausentes: 2 },
  { label: "Qui", presentes: 21, ausentes: 0 },
  { label: "Sex", presentes: 17, ausentes: 4 },
];

export const entryDistribution: HourDistributionPoint[] = [
  { label: "07h", registros: 4 },
  { label: "08h", registros: 14 },
  { label: "09h", registros: 5 },
  { label: "10h", registros: 1 },
];
