/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminRegistrosRouteImport } from './routes/_authenticated/admin/registros'
import { Route as AuthenticatedAdminLocaisRouteImport } from './routes/_authenticated/admin/locais'
import { Route as AuthenticatedAdminFuncionariosRouteImport } from './routes/_authenticated/admin/funcionarios'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRegistrosRoute =
  AuthenticatedAdminRegistrosRouteImport.update({
    id: '/admin/registros',
    path: '/admin/registros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLocaisRoute =
  AuthenticatedAdminLocaisRouteImport.update({
    id: '/admin/locais',
    path: '/admin/locais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFuncionariosRoute =
  AuthenticatedAdminFuncionariosRouteImport.update({
    id: '/admin/funcionarios',
    path: '/admin/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/locais': typeof AuthenticatedAdminLocaisRoute
  '/admin/registros': typeof AuthenticatedAdminRegistrosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/admin/locais': typeof AuthenticatedAdminLocaisRoute
  '/admin/registros': typeof AuthenticatedAdminRegistrosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/funcionarios': typeof AuthenticatedAdminFuncionariosRoute
  '/_authenticated/admin/locais': typeof AuthenticatedAdminLocaisRoute
  '/_authenticated/admin/registros': typeof AuthenticatedAdminRegistrosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/funcionarios'
    | '/admin/locais'
    | '/admin/registros'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/funcionarios'
    | '/admin/locais'
    | '/admin/registros'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/funcionarios'
    | '/_authenticated/admin/locais'
    | '/_authenticated/admin/registros'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/registros': {
      id: '/_authenticated/admin/registros'
      path: '/admin/registros'
      fullPath: '/admin/registros'
      preLoaderRoute: typeof AuthenticatedAdminRegistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/locais': {
      id: '/_authenticated/admin/locais'
      path: '/admin/locais'
      fullPath: '/admin/locais'
      preLoaderRoute: typeof AuthenticatedAdminLocaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/funcionarios': {
      id: '/_authenticated/admin/funcionarios'
      path: '/admin/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AuthenticatedAdminFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminFuncionariosRoute: typeof AuthenticatedAdminFuncionariosRoute
  AuthenticatedAdminLocaisRoute: typeof AuthenticatedAdminLocaisRoute
  AuthenticatedAdminRegistrosRoute: typeof AuthenticatedAdminRegistrosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminFuncionariosRoute: AuthenticatedAdminFuncionariosRoute,
  AuthenticatedAdminLocaisRoute: AuthenticatedAdminLocaisRoute,
  AuthenticatedAdminRegistrosRoute: AuthenticatedAdminRegistrosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
