// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmqimpmlnepaqoplsxtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcWltcG1sbmVwYXFvcGxzeHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI3MjA0NzAsImV4cCI6MjA5ODI5NjQ3MH0.x85fPVr6N_V17ZKuqXP-HHsuP5JFJ6OH1tz6zNtpCtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});